name: Deploy UAT

on:
  push:
    branches:
      - uat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /var/www/sites/hsbc-touchscreen-test
            git reset --hard
            git pull
            git lfs pull
            npm install
            npm run build
          host: ${{ secrets.UAT_HOST }}
          username: ${{ secrets.UAT_USERNAME }}
          privateKey: ${{ secrets.UAT_PRIVATE_KEY }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEPLOYMENTS }}
